apiVersion: skaffold/v3
kind: Config
metadata:
  name: daywriter-app
build:
  artifacts:
    - image: daywriter
      context: .
      docker:
        dockerfile: ./src/DayWriter/Dockerfile
        buildArgs:
          SOURCE_DIR: "dist"
manifests:
  helm:
    releases:
      - name: daywriter
        chartPath: ./src/helm-chart
        createNamespace: true
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO}}"
          image.tag: "{{.IMAGE_TAG}}"
        setValues:
          postgresql.database: "daywriter"
          postgresql.appUsername: "dw_owner"
          postgresql.volumeMountPath: "/bitnami/postgresql"
deploy:
  helm: {}
  statusCheckDeadlineSeconds: 120

profiles:

  - name: development
    patches:
      - op: add
        path: /manifests/helm/releases/0/namespace
        value: development
      - op: add
        path: /manifests/helm/releases/0/setValues/env
        value: "development"
      - op: add
        path: /manifests/helm/releases/0/setValues/replicaCount
        value: 1
      - op: add
        path: /manifests/helm/releases/0/setValues/postgresql.volumeClaimStorageResourceRequest
        value: "1Gi"
      - op: add
        path: /manifests/helm/releases/0/setValues/podDisruptionBudget.minAvailable
        value: 1

  - name: production
    patches:
      - op: add
        path: /manifests/helm/releases/0/namespace
        value: production
      - op: add
        path: /manifests/helm/releases/0/setValues/env
        value: "production"
      - op: add
        path: /manifests/helm/releases/0/setValues/replicaCount
        value: 3
      - op: add
        path: /manifests/helm/releases/0/setValues/postgresql.volumeClaimStorageResourceRequest
        value: "10Gi"
      - op: add
        path: /manifests/helm/releases/0/setValues/podDisruptionBudget.minAvailable
        value: 2
