apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "daywriter.fullname" . }}-postgresql
  labels:
    {{- include "daywriter.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgresql

  minAvailable: {{ .Values.postgresql.pdbMinAvailable | default 1 }}
