apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    {{- include "daywriter.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql

  clusterIP: None
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      protocol: TCP
      targetPort: postgresql
