apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    {{- include "daywriter.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: postgresql
  serviceName: {{ .Release.Name }}-postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: postgresql
    spec:
      nodeSelector:
        env: {{ .Values.env | quote }}

      affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: postgresql
                    app.kubernetes.io/instance: {{ .Release.Name }}
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: postgresql
          env:
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgresql.database | quote }}
            # App user - created by Bitnami with POSTGRESQL_USERNAME/PASSWORD
            - name: POSTGRESQL_USERNAME
              value: {{ .Values.postgresql.appUsername | quote }}
            - name: POSTGRESQL_PASSWORD
              {{- if .Values.postgresql.appPasswordSecretKeyRefName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.appPasswordSecretKeyRefName }}
                  key: {{ .Values.postgresql.appPasswordSecretKeyRefKey }}
                  optional: false
              {{- else }}
              value: {{ randAlphaNum 32 | quote }}
              {{- end }}
            # Admin (postgres superuser) password
            - name: POSTGRESQL_POSTGRES_PASSWORD
              {{- if .Values.postgresql.adminPasswordSecretKeyRefName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.adminPasswordSecretKeyRefName }}
                  key: {{ .Values.postgresql.adminPasswordSecretKeyRefKey }}
                  optional: false
              {{- else }}
              value: {{ randAlphaNum 32 | quote }}
              {{- end }}
            - name: POSTGRESQL_VOLUME_DIR
              value: {{ .Values.postgresql.volumeMountPath | quote }}
            - name: POSTGRESQL_PORT
              value: {{ .Values.postgresql.port | quote }}
            - name: POSTGRESQL_REPLICATION_USER
              value: {{ .Values.postgresql.replUsername | default .Values.postgresql.appUsername | quote }}
            - name: POSTGRESQL_REPLICATION_PASSWORD
              {{- if .Values.postgresql.replPasswordSecretKeyRefName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.replPasswordSecretKeyRefName }}
                  key: {{ .Values.postgresql.replPasswordSecretKeyRefKey }}
                  optional: false
              {{- else }}
              value: {{ randAlphaNum 32 | quote }}
              {{- end }}

          image: "{{ .Values.postgresql.imageRepository }}:{{ .Values.postgresql.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres -h 127.0.0.1 -p {{ .Values.postgresql.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres -h 127.0.0.1 -p {{ .Values.postgresql.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: {{ .Values.postgresql.volumeMountPath }}
      tolerations:
        - key: {{ .Values.env | quote }}
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        {{- with .Values.extraTolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          {{- toYaml .Values.postgresql.volumeClaimAccessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.postgresql.volumeClaimStorageResourceRequest }}
